Version1.0/webDevUser36.html
Made all necessary changes to complete part.
=> V.1.0 web dev 36

Version1.0/webDevUser36.html
=> Version1.0/webDevUser36.html

Version1.0/webDevUser13.html
=> Version1.0/webDevUser13.html

Version1.0/will anderson's.html
All changes were made to complete V1.0
=> V1.0 User 0

Version1.0/webDevUser32.html
added introductory information to my home page
=> #32 thingy

Version2.0/JackStensrudsversion2.0.26.html
Changes backround and adds face section and more
=> Update on 1.2B assigmentJackStensrudsversion2.0.26.html

Version2.0/webDevUser27.html
=> Smiley face

Version2.0/webDevUser18.html
I've created my webpage, added my headers, elements and my customized smiley face.
=> Activity 1.2b

Version2.0/webDevUser07.html
I added the smile face to the code.
=> Day 6 1.2b

Version2.0/webDevUser24.html
=> i madede a smiley face'

Version2.0/style.css, Version2.0/webDevUser19.html
=> update user 19

Version3.0/user26/aboutMe.html
=> Created aboutMe.html

Version3.0/user07/Music.html, Version3.0/user07/aboutMe.html, Version3.0/user07/list.html
I did all the steps and did the pull request
=> Day 12 1.3c

Version4.0/user26/display.html
=> Create display.html 

Version4.0/user18/CSS/gallery.css, Version4.0/user18/CSS/rainbow.css, Version4.0/user18/CSS/style.css, Version4.0/user18/display.html, Version4.0/user18/gallery.html, Version4.0/user18/index.html, Version4.0/user18/portfolio.html
I've created the display.html, gallery.html, portfolio.html and, the index.html. From here I just need to pull request and I'm completed with my assignments.
=> Created multiple new htmls.

Version2.0/webDevUser36.html, Version4.0/user27/CSS/portfolio.html, Version4.0/user27/CSS/style.css, Version4.0/user27/display.html, Version4.0/user27/index.html
Today i learned how to animate cards and make different fonts appear and other things like that all with css
=> CSS animations

Version4.0/user19/CSS/style.css, Version4.0/user19/display.html, Version4.0/user19/index.html
=> updated user 19

Version4.0/user07/CSS/style.css, Version4.0/user07/Display.html, Version4.0/user07/Gallery.html, Version4.0/user07/portfolio.html
I did the stuff for this assignment
=> day 17 1.4b

Version5.0/user19/index.html
=> updated user19

Version4.0/user10/CSS/style.css, Version4.0/user10/portfolio.html
=> Created these two for 1.4c pull

Version4.0/user06/CSS/portfoilo.html, Version4.0/user06/CSS/rainbow.CSS, Version4.0/user06/CSS/style.css, Version4.0/user06/display.html, Version4.0/user06/index.html, Version5.0/user06/JS/index.html
=> Pull request

Version4.0/user00/CSS/style.css, Version4.0/user17/CSS/rainbow.css, Version4.0/user17/CSS/style.css, Version4.0/user17/display.html, Version4.0/user17/gallery.css, Version4.0/user17/portfolio.html
=> Day 17 Activity 1.4d CSS Animations

Version5.0/user19/index.html
=> updated user 19 Day 18 Activity 1.5a

Version5.0/user19/index.html
Day 19 Activity 1.5b Somethings Afoot
=> Day 19 Activity 1.5b Somethings Afoot

Version5.0/user22/menu.html, Version6.0/user22/navbar.html
1.5b and 1.5d adjusted, worked, and moved to the correct spots
=> 1.5b moved and 1.5d done

Version4.0/user18/CSS/style.css, Version4.0/user18/footer.html, Version4.0/user18/framework.html, Version4.0/user18/navbar.html, Version6.0/user18/CSS/style.css, Version6.0/user18/eps.html, Version6.0/user18/genres.html, Version6.0/user18/index.html, Version6.0/user18/singles.html, Version6.0/user18/unranked.html
Created my final draft of my static website, I've added multiple pages and completed requirements necessary.
=> 1.6 Static Website

Version6.0/user03/CSS/style.css, Version6.0/user03/about.html, Version6.0/user03/archive.html, Version6.0/user03/gallery.html, Version6.0/user03/jokewebsite.html, Version6.0/user03/submit.html
=> rebuilt the css style

Version7.0/user08/JS/script.js, Version7.0/user08/games.html, Version7.0/user08/index.html, Version7.0/user08/script.html
One of the licks for 1.7A was for sale
=> Javascript

Version6.0/user25/faq.html
Added dark mode and other cool features
=> Add Jquery
